### ISSUE TITLE
X12Validator example needs a tuple with 3 elements

### ISSUE THREAD

**Issue by k-simmons2** [copyleftdev/x12-edi-tools#1]
There is a minor error in readme.md X12Validator example. This line throws the exception "too many values to unpack (expected 2)".
``is_valid, errors = validator.validate("path/to/x12_file.edi")``

It should have 3 elements like:
``is_valid, errors, warnings = validator.validate("path/to/x12_file.edi")``

**Comment by copyleftdev** [comment]
updated , thanks
